#ifndef REQUEST_LISTENER_CALCULATE_DECISION_H
#define REQUEST_LISTENER_CALCULATE_DECISION_H

#include <stdio.h>
#include <stddef.h>
#include <stdint.h>

#include "request_listener.h"

typedef enum {
    REQLIST_DECISION_CLEAR_ALL_USERS = 9,
    REQLIST_DECISION_GET_ALL_USERS = 8,
    REQLIST_DECISION_SET_USER = 7,
    REQLIST_DECISION_GET_USER_ID = 6,
    REQLIST_DECISION_GET_USER = 5,
    REQLIST_DECISION_GET_DATASET = 4,
    REQLIST_DECISION_SET_DATASET = 3,
    REQLIST_DECISION_ENABLE_POL = 2,
    REQLIST_DECISION_GET_POLICY_LIST = 1,
    REQLIST_DECISION_VALID_REQUEST = 0,
    REQLIST_DECISION_ERROR = -1,
    REQLIST_DECISION_ERROR_JSON_NULL = -2,
    REQLIST_DECISION_ERROR_CMD_NOT_FND = -3,
    REQLIST_DECISION_ERROR_POLID_NOT_FND = -4,
    REQLIST_DECISION_ERROR_NEQ_RESOLVE = -5,
    REQLIST_DECISION_ERROR_USRID_NOT_FND = -6,
    REQLIST_DECISION_ERROR_DATASET_LIST_NOT_FND = -7,
    REQLIST_DECISION_ERROR_GETUSR_NOT_FND = -8,
    REQLIST_DECISION_ERROR_GETUSRID_NOT_FND = -9,
    REQLIST_DECISION_ERROR_REGUSR_NOT_FND = -10
} REQLIST_DECISION_error_e;

uint8_t request_listener_calculate_decision(char *req, size_t reqlen, char *res, size_t *reslen);

int8_t request_listener_check_request(const char *req);

#endif  // REQUEST_LISTENER_CALCULATE_DECISION_H
